FROM hblasins/image-preprocess
MAINTAINER Henryk Blasinski <hblasins@stanford.edu>

RUN apt-get -qq update && apt-get -qq install -y \
    unzip \
    dcraw \
    xorg \
    wget \
    curl && \
    mkdir 

